name: dbt_27_Apr
version: 1.0.0
config-version: 2
profile: dbt_27_Apr
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
models:
  dbt_27_Apr:
    +materialized: view
