dbt_27_Apr:
  target: dev
  outputs:
    dev:
      type: snowflake
      role: ACCOUNTADMIN
      warehouse: COMPUTE_WH
      database: DBT_HOME
      schema: DBT_CI_CD
      threads: 8
    prod:
      type: snowflake
      role: ACCOUNTADMIN
      warehouse: COMPUTE_WH
      database: DB_DBT_DESTI
      schema: DBT_CI_CD_PRD
      threads: 8
